services:
  app:
    container_name: node14-prisma-mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4023:4000
    volumes: 
      - ./:/app
  db:
    container_name: js-project-prisma-myslq
    image: mysql:8.0.23
    environment:
      # Optional to create a new user and password
      # Granted superuser permission by default
      MYSQL_USER: test
      MYSQL_PASSWORD: Password123
      # root password is required
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: profiles
    ports:
      - 5007:3306
      