services:
  app:
    container_name: prisma-mysql-ts
    build:
      context: .
      dockerfile: Dockerfile
    image: node:14-alpine
    ports:
      - 5001:4000
    volumes: 
      - ./:/app
    depends_on:
      - db
    links:
      - db
    networks:
      - backend
    
  db:
    container_name: prisma-mysql-ts-db
    image: mysql:8.0.23
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      # Optional to create a new user and password
      # Granted superuser permission by default
      MYSQL_USER: test
      MYSQL_PASSWORD: Password123
      # root password is required
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: prisma
    ports:
      - 5007:3306
    networks:
      - backend

networks:
  backend:
