services:
  app:
    container_name: prisma-mysql-ts
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:4000
    volumes: 
      - ./:/app
    depends_on:
      - db
    
  db:
    container_name: prisma-mysql-ts-db
    image: mysql:8.0.23 # Version to be updated to match Aurora
    environment:
      # Optional to create a new user and password
      # Granted superuser permission by default
      MYSQL_USER: test
      MYSQL_PASSWORD: Password123
      # root password is required
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: prisma
    ports:
      - 5007:3306
