services:
  # app:
  #   container_name: typeorm-mysql-ts
  #   # build:
  #   #   context: .
  #   #   dockerfile: Dockerfile
  #   image: node:14-alpine
  #   ports:
  #     - 5002:4000
  #   volumes: 
  #     - ./:/app
  #   depends_on:
  #     - db
    
  db:
    container_name: typeorm-mysql-ts-db
    # Set SQL mode to avoid FULL_GROUP_BY
    command: --default-authentication-plugin=mysql_native_password --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    image: mysql:8.0.23 # Version to be updated to match Aurora
    environment:
      # Optional to create a new user and password
      # Granted superuser permission by default
      MYSQL_USER: test
      MYSQL_PASSWORD: Password123
      # root password is required
      MYSQL_ROOT_PASSWORD: Password123
      MYSQL_DATABASE: typeorm
    ports:
      - 5008:3306
