services:
  app:
    container_name: node14-apollo-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:4000
    volumes: 
      - ./:/app:delegated
      - /app/node_modules
